# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='分類辭典',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('語詞編號', models.CharField(max_length=200, unique=True)),
                ('噶哈巫語教材標記法', models.CharField(blank=True, max_length=200)),
                ('噶哈巫語潘永歷標記法', models.CharField(blank=True, max_length=200)),
                ('中文譯解', models.CharField(blank=True, max_length=200)),
                ('臺語譯解', models.CharField(blank=True, max_length=200)),
                ('備註', models.CharField(blank=True, max_length=200)),
                ('出處', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
