# Generated by Django 4.2.1 on 2023-05-24 08:18

from django.db import migrations, models
import 族語辭典.models


class Migration(migrations.Migration):

    dependencies = [
        ('族語辭典', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='分類辭典',
            name='噶哈巫音檔',
            field=models.FileField(editable=False, null=True, storage=族語辭典.models.NgaungawStorage(), upload_to=''),
        ),
        migrations.AddField(
            model_name='分類辭典',
            name='臺語音檔',
            field=models.FileField(editable=False, null=True, storage=族語辭典.models.NgaungawStorage(), upload_to=''),
        ),
        migrations.AddField(
            model_name='分類辭典',
            name='華語音檔',
            field=models.FileField(editable=False, null=True, storage=族語辭典.models.NgaungawStorage(), upload_to=''),
        ),
        migrations.AddField(
            model_name='分類辭典',
            name='語詞編號音檔',
            field=models.FileField(editable=False, null=True, storage=族語辭典.models.NgaungawStorage(), upload_to=''),
        ),
    ]
